[package]
name = "secret-u"
version = "0.1.0"
authors = ["Christopher Haster <christopher.haster@arm.com>"]
edition = "2018"

[features]
# show VM execution
trace = []

[dependencies]
thiserror = "1.0.25"
paste = "1.0.5"
